---
title: "Spectrum cancer_transcriptional_programs"
author: "Mobina Kazemi"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: true
    code-tools: true
    code-link: true
    toc: true
execute:
  cache: false
---

```{r setup}
#| output: false
library(UCell)
library(ggplot2)
library(zellkonverter)
library(Seurat)
library(cowplot)
library(tidyverse)
library(reticulate)
library(ggthemes)
library(dittoSeq)
library(patchwork)
library(anndata)
library(Matrix)
library(glue)
library(ggplotify)
library(ggh4x)
library(here)
library(leidenbase)
library(ggpubr)
library(SeuratDisk)
#library(bsub)
```


```{r}
SCE<-readRDS("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/Ovarian.cancer.super_processed_filtered_annotated.rds")
SCE<-SCE[,which(SCE@meta.data$doublet=="False")]
#adata<-read_h5ad("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/Ovarian_cancer_no_doublet.h5ad")
```

```{r}
meta_programs<-read.delim("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/data/cancer_metaprograms.csv",sep = ",")
```

```{python}
import pandas
    
    
meta_program_dict = {}
for m in r.meta_programs.columns:
    for j in range(49):
      meta_program_dict.setdefault(m, []).append(r.meta_programs[m].values[j])     
```


```{r}
meta_program_dict_r=py$meta_program_dict


scores <- AddModuleScore_UCell(SCE, features=meta_program_dict_r)

scores@meta.data$site<-0
scores@meta.data$site[grep("BOWEL",scores@meta.data$sample)]<-"BOWEL"
scores@meta.data$site[grep("ADNEXA",scores@meta.data$sample)]<-"ADNEXA"
scores@meta.data$site[grep("OMENTUM",scores@meta.data$sample)]<-"OMENTUM"
scores@meta.data$site[grep("QUADRANT",scores@meta.data$sample)]<-"QUADRANT"
scores@meta.data$site[grep("PERITONEUM",scores@meta.data$sample)]<-"PERITONEUM"
scores@meta.data$site[grep("ASCITES",scores@meta.data$sample)]<-"ASCITES"
scores@meta.data$site[grep("OVARY",scores@meta.data$sample)]<-"OVARY"
scores@meta.data$site[grep("DIAPHRAGM",scores@meta.data$sample)]<-"DIAPHRAGM"
scores@meta.data$site[grep("STOMACH",scores@meta.data$sample)]<-"STOMACH"
scores@meta.data$site[grep("CECUM",scores@meta.data$sample)]<-"CECUM"
scores@meta.data$site[grep("TUBE",scores@meta.data$sample)]<-"TUBE"
scores@meta.data$site[grep("TUMOUR",scores@meta.data$sample)]<-"TUMOUR"
scores@meta.data$site[grep("PELVIS",scores@meta.data$sample)]<-"PELVIS"
scores@meta.data$site[grep("SURFACE",scores@meta.data$sample)]<-"SURFACE"
scores@meta.data$site[grep("LYMPH_NODE",scores@meta.data$sample)]<-"LYMPH_NODE"
scores@meta.data$site[grep("LYMPH_NODE_WITH_COLONIC_MESENTARY",scores@meta.data$sample)]<-"LYMPH_NODE_WITH_COLONIC_MESENTARY"
scores@meta.data$site[grep("ANTERIOR_ABDOMINAL_WALL",scores@meta.data$sample)]<-"ANTERIOR_ABDOMINAL_WALL"
scores@meta.data$site[grep("PARACOLIC_GUTTER",scores@meta.data$sample)]<-"PARACOLIC_GUTTER"
scores@meta.data$site[grep("BLADDER",scores@meta.data$sample)]<-"BLADDER"

scores@meta.data$patient<-scores@meta.data$patient_id

data.sce <- as.SingleCellExperiment(scores)
adata<-SCE2AnnData(data.sce)
adata$obs["patient"]
write_h5ad(adata,"/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL_scores_seurat.h5ad")

class(scores@meta.data$patient)
scores@meta.data$patient<-as.factor(scores@meta.data$patient)
scores@meta.data$patient_id<-as.factor(scores@meta.data$patient_id)
SaveH5Seurat(scores, filename = "/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL_scores_seurat.h5Seurat")
#Convert("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL_scores_seurat.h5Seurat", dest = "h5ad")

1+1
```

```{python}
import scanpy as sc
adata=sc.read("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL_scores_seurat.h5ad")

adata_full=r.adata

adata.obs
meta_programs_list=["MP1..Cell.Cycle...G2.M_UCell", "MP2..Cell.Cycle...G1.S_UCell"]

,
       'MP3..Cell.Cylce.HMG.rich_UCell', 'MP4..Chromatin_UCell',
       'MP5.Stress_UCell', 'MP6.Hypoxia_UCell', 'MP7.Stress..in.vitro._UCell',
       'MP8.Proteasomal.degradation_UCell',
       'MP9.Unfolded.protein.response_UCell', 'MP10.Protein.maturation_UCell',
       'MP11.Translation.initiation_UCell', 'MP12.EMT.I_UCell',
       'MP13.EMT.II_UCell', 'MP14.EMT.III_UCell', 'MP15.EMT.IV_UCell',
       'MP16.MES..glioma._UCell', 'MP17.Interferon.MHC.II..I._UCell',
       'MP18.Interferon.MHC.II..II._UCell', 'MP19.Epithelial.Senescence_UCell',
       'MP20.MYC_UCell', 'MP21.Respiration_UCell', 'MP22.Secreted.I_UCell',
       'MP23.Secreted.II_UCell', 'MP24.Cilia_UCell', 'MP25.Astrocytes_UCell',
       'MP26.NPC.Glioma_UCell', 'MP27.Oligo.Progenitor_UCell',
       'MP28.Oligo.normal_UCell', 'MP29.NPC.OPC_UCell',
       'MP30.PDAC.classical_UCell', 'MP31.Alveolar_UCell',
       'MP32.Skin.pigmentation_UCell', 'MP33.RBCs_UCell',
       'MP34.Platelet.activation_UCell', 'MP35.Hemato.related.I_UCell',
       'MP36.IG_UCell', 'MP37.Hemato.related.II_UCell',
       'MP38.Glutathione_UCell', 'MP39.Metal.response_UCell',
       'MP40.PDAC.related_UCell', 'MP41.Unassigned_UCell']
       
       
       
sc.tl.dendrogram(adata, groupby='patient')       
sc.pl.matrixplot(adata, meta_programs_list, groupby='patient_id', dendrogram=True)


```

```{r}
write.table(scores@meta.data[,c(17,seq(109,149))],file = "/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/meta_pathway_scores_UCELL.txt")

data2<-scores@meta.data
write.table(data2,file = "/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/Data2_meta_pathway_scores_UCELL.txt")


Data<-data2[,1:109]
Data$meta_program<-colnames(Data)[109]
colnames(Data)[109]<-"Score"


for(i in 110:149){
 a<-data2[,c(1:108,i)]
 a$meta_program<-colnames(a)[109]
 colnames(a)[109]<-"Score"
 Data<-rbind(Data,a)

}

Data$site<-0

#c("OMENTUM","QUADRANT","PERITONEUM","ASCITES","OVARY","DIAPHRAGM","STOMACH","BOWEL","ADNEXA","CECUM","TUBE","TUMOUR","PELVIS","SURFACE","LYMPH_NODE","LYMPH_NODE_WITH_COLONIC_MESENTARY","ANTERIOR_ABDOMINAL_WALL","PARACOLIC_GUTTER","BLADDER")

Data$site[grep("BOWEL",Data$sample)]<-"BOWEL"
Data$site[grep("ADNEXA",Data$sample)]<-"ADNEXA"
Data$site[grep("OMENTUM",Data$sample)]<-"OMENTUM"
Data$site[grep("QUADRANT",Data$sample)]<-"QUADRANT"
Data$site[grep("PERITONEUM",Data$sample)]<-"PERITONEUM"
Data$site[grep("ASCITES",Data$sample)]<-"ASCITES"
Data$site[grep("OVARY",Data$sample)]<-"OVARY"
Data$site[grep("DIAPHRAGM",Data$sample)]<-"DIAPHRAGM"
Data$site[grep("STOMACH",Data$sample)]<-"STOMACH"
Data$site[grep("CECUM",Data$sample)]<-"CECUM"
Data$site[grep("TUBE",Data$sample)]<-"TUBE"
Data$site[grep("TUMOUR",Data$sample)]<-"TUMOUR"
Data$site[grep("PELVIS",Data$sample)]<-"PELVIS"
Data$site[grep("SURFACE",Data$sample)]<-"SURFACE"
Data$site[grep("LYMPH_NODE",Data$sample)]<-"LYMPH_NODE"
Data$site[grep("LYMPH_NODE_WITH_COLONIC_MESENTARY",Data$sample)]<-"LYMPH_NODE_WITH_COLONIC_MESENTARY"
Data$site[grep("ANTERIOR_ABDOMINAL_WALL",Data$sample)]<-"ANTERIOR_ABDOMINAL_WALL"
Data$site[grep("PARACOLIC_GUTTER",Data$sample)]<-"PARACOLIC_GUTTER"
Data$site[grep("BLADDER",Data$sample)]<-"BLADDER"



Data2<-Data[which(Data$site %in% c("BOWEL","ADNEXA")),]



p0=ggplot(Data2, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA,position = position_dodge(width = 0.8),width=0.6)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))

# scale y limits based on ylim1

p1 = p0 + scale_y_continuous(limits = quantile(Data2$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(Data2$Score, c(0.1, 0.9)))








# Box plot: comparison against reference

stat.test <-compare_means(
  Score ~ site, data = Data2, group.by = "meta_program",
  method = "t.test", ref.group = "ADNEXA"
)

p1=p1 + stat_pvalue_manual(
  stat.test, x = "meta_program", y.position = as.numeric(quantile(Data2$Score, c(0.1, 0.9))[2]),
  label = "p.signif",size = 3.5,color = "red",tip.length = 10,
  bracket.shorten = 10,hide.ns = TRUE)
p1
# Box plots
p1
pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_score_Adnexa_Bowel_with_statistics_UCELL.pdf",width = 20,height = 10)
p1 
dev.off()

```

```{r}
Data2<-Data[which(Data$site %in% c("OMENTUM","ADNEXA")),]

#library(gg.layers)
library(ggplot2)
#facet_wrap( ~ meta_program, scales="free")+ geom_boxplot2(width = 0.8, width.errorbar = 0.5)
#geom_point(aes(y=Score, group=site), position = position_dodge(width=0.75))

p0=ggplot(Data2, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA,position = position_dodge(width = 0.8),width=0.6)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))

# scale y limits based on ylim1

p1 = p0 + scale_y_continuous(limits = quantile(Data2$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(Data2$Score, c(0.1, 0.9)))




# Box plot: comparison against reference

stat.test <-compare_means(
  Score ~ site, data = Data2, group.by = "meta_program",
  method = "t.test", ref.group = "ADNEXA"
)

p1=p1 + stat_pvalue_manual(
  stat.test, x = "meta_program", y.position =  as.numeric(quantile(Data2$Score, c(0.1, 0.9))[2]),
  label = "p.signif",size = 3.5,color = "red",tip.length = 10,
  bracket.shorten = 10,hide.ns = TRUE)
p1
# Box plots

pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_score_Adnexa_OMENTUM_with_statistics_UCELL.pdf",width = 20,height = 10)
p1 
dev.off()
```



```{r}
Data2<-Data[which(Data$site %in% c("BOWEL","ADNEXA")),]


pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_score_Adnexa_BOWEL_patients_UCELL.pdf",width = 20,height = 10)
for(i in 1:length(unique((Data2$patient)))){
patient=as.character((unique((Data2$patient)))[i])
a<-Data2[which(Data2$patient==patient),]

p0=ggplot(a, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))
p1 = p0 + scale_y_continuous(limits = quantile(a$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(a$Score, c(0.1, 0.9)))

if(length(table(a$site))==2){
stat.test <-compare_means(
  Score ~ site, data = a, group.by = "meta_program",
  method = "t.test", ref.group = "ADNEXA")

p1=p1 + stat_pvalue_manual(
  stat.test, x = "meta_program", y.position = as.numeric(quantile(a$Score, c(0.1, 0.9))[2]),
  label = "p.signif",size = 3.5,color = "red",tip.length = 10,
  bracket.shorten = 10,hide.ns = TRUE)+ggtitle(paste0("Patient: ",patient))
print(p1)
}
else{
  p1=p1+ggtitle(paste0("Patient: ",patient))
  print(p1)
}

}

dev.off()
```

```{r}
Data2<-Data[which(Data$site %in% c("OMENTUM","ADNEXA")),]
vec=c()

pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_score_Adnexa_OMENTUM_patients_UCELL.pdf",width = 20,height = 10)
for(i in 1:length(unique((Data2$patient)))){
patient=as.character((unique((Data2$patient)))[i])
a<-Data2[which(Data2$patient==patient),]

p0=ggplot(a, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))
p1 = p0 + scale_y_continuous(limits = quantile(a$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(a$Score, c(0.1, 0.9)))

if(length(table(a$site))==2 && as.numeric(table(a$site)[2])>50 && as.numeric(table(a$site)[1])>50){
stat.test <-compare_means(
  Score ~ site, data = a, group.by = "meta_program",
  method = "t.test", ref.group = "ADNEXA")

p1=p1 + stat_pvalue_manual(
  stat.test, x = "meta_program", y.position = as.numeric(quantile(a$Score, c(0.1, 0.9))[2]),
  label = "p.signif",size = 3.5,color = "red",tip.length = 10,
  bracket.shorten = 10,hide.ns = TRUE)+ggtitle(paste0("Patient: ",patient))
print(p1)
}
else{
  p1=p1+ggtitle(paste0("Patient: ",patient))
  print(p1)
}

}

dev.off()

```

```{r}
Data2<-Data[which(Data$site %in% c("BOWEL","ADNEXA")),]
data_median=Data2 %>% group_by(sample,meta_program) %>% summarise(Score = median(Score, na.rm = TRUE))
data_median$site<-0
data_median$site[grep("BOWEL",data_median$sample)]<-"BOWEL"
data_median$site[grep("ADNEXA",data_median$sample)]<-"ADNEXA"


p0=ggplot(data_median, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA,position = position_dodge(width = 0.8),width=0.6)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))

# scale y limits based on ylim1
p0
p1 = p0 + scale_y_continuous(limits = quantile(data_median$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(data_median$Score, c(0.1, 0.9)))+ggtitle("Score: Median_Score_Over_Samples")

p1


pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_median_over_samples_Adnexa_BOWEL_UCELL.pdf",width = 20,height = 10)
p1 
dev.off()


```


```{r}
Data2<-Data[which(Data$site %in% c("OMENTUM","ADNEXA")),]
data_median=Data2 %>% group_by(sample,meta_program) %>% summarise(Score = median(Score, na.rm = TRUE))
data_median$site<-0
data_median$site[grep("OMENTUM",data_median$sample)]<-"OMENTUM"
data_median$site[grep("ADNEXA",data_median$sample)]<-"ADNEXA"


p0=ggplot(data_median, aes(x = meta_program, y = Score)) +  # ggplot function
  geom_boxplot(aes(fill=site),outlier.shape = NA,position = position_dodge(width = 0.8),width=0.6)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(angle=0))

# scale y limits based on ylim1
p0
p1 = p0 + scale_y_continuous(limits = quantile(data_median$Score, c(0.1, 0.9)))+coord_cartesian(ylim = quantile(data_median$Score, c(0.1, 0.9)))+ggtitle("Score: Median_Score_Over_Samples")

p1


pdf("/work/shah/users/Mobina/Projects/SPECTRUM_NACT/Spectrum_Full/UCELL/meta_program_median_over_samples_Adnexa_OMENTUM_UCELL.pdf",width = 20,height = 10)
p1 
dev.off()
```

